routes:
  /:
    uses: DashboardController@index
    as: seopro.dashboard

  defaults:
    uses: DefaultsController@edit
    as: seopro.defaults.edit
  post@defaults:
    uses: DefaultsController@update
    as: seopro.defaults.update

  sections:
    uses: SectionController@index
    as: seopro.sections.index

  sections/pages:
    uses: PagesController@edit
    as: seopro.pages.edit
  post@sections/pages:
    uses: PagesController@update
    as: seopro.pages.update

  sections/collections/{collection}:
    uses: CollectionController@edit
    as: seopro.collections.edit
  post@sections/collections/{collection}:
    uses: CollectionController@update
    as: seopro.collections.update

  sections/taxonomies/{collection}:
    uses: TaxonomyController@edit
    as: seopro.taxonomies.edit
  post@sections/taxonomies/{collection}:
    uses: TaxonomyController@update
    as: seopro.taxonomies.update

  humans:
    uses: HumansController@edit
    as: seopro.humans.edit
  post@humans:
    uses: HumansController@update
    as: seopro.humans.update

  reports:
    uses: ReportController@index
    as: seopro.reports.index
  post@reports:
    uses: ReportController@store
    as: seopro.reports.store
  reports/{report}:
    uses: ReportController@show
    as: seopro.reports.show
