sections:

  images:
    fields:
      asset_container:
        type: asset_container
        allow_blank: true
      og_image_dimensions:
        type: section
      open_graph_image_width:
        type: integer
        width: 50
      open_graph_image_height:
        type: integer
        width: 50

  sitemap:
    fields:
      sitemap_enabled:
        type: toggle
      sitemap_url:
        type: text
      sitemap_cache_length:
        type: integer
